export default {
  '401': 'NOT_AUTHORIZED',
  '403': 'FORBIDDEN',
  '404': 'PAGE_NOT_FOUND',
  '405': 'METHOD_NOT_ALLOWED',
  '422': 'UNPROCESSABLE_ENTITY',
  '429': 'TOO_MANY_REQUESTS',
  '500': 'SERVER_ERROR',
  '503': 'SERVICE_UNAVAILABLE',
  '505': 'BAR_GATEWAY'
};
